### PR TITLE
Fix - esp32c6 support as MCU

### PR DESCRIPTION
**Pull request by Nassiel**
Modified the chip and build to support the new MCU
1. Added support for MCU esp32c6
2. Disabled autodiscovery for Risc target

### CODE REVIEW

**Comment by ivmarkov** [comment]
I've implemented similar changes to the proposed here, yet I had to extend the fixes a bit so that the used GCC is correctly detected and there is no need to set CC flags.

As for MCU auto-discovery - I've lowered this to a Cargo build warning. I don't want to set all builds to fail if `MCU` is not defined, and anyway most of the folks are still running with esp32c3 w.r.t. riscv MCUs; c3 is picked as the default MCU if the user has not specified an MCU for a riscv target, and furthermore, a visible build warning is issued in that case.

**Comment by Nassiel** [comment]
Thanks, imho, the template creator should ask for the target model from a list and write down the mcu variable for further iterations and precision/control of the developer.

**Comment by ivmarkov** [comment]
> Thanks, imho, the template creator should ask for the target model from a list and write down the mcu variable for further iterations and precision/control of the developer.

I do not understand what you are saying. Can you elaborate?

**Comment by Nassiel** [comment]
In both repositories, esp-template and esp-idf-template, I think this [file](https://github.com/esp-rs/esp-idf-template/blob/master/cargo/.cargo/config.toml) should have the condition to add based on the input from the user, the correct MCU variable by default. 

By that, you can keep this autodiscovery functionality as a secondary utility but start to provide an explicit reference in new projects for the MCU so, let's say, 'we' start some good practices among the future developers and not entirely rely in an auto-discover that in case of failure, it's a very 'black-box' function and you can get frustrated. 

Mostly based on my recent experience, where it took days to detect that the bootloader used was the C3 instead of C6 because nothing in the process tells you that. That opaque behaviour simplifies, yes, only if they are extremely resilient but in case of failure, god bless you to find the proper alternative.

In the end, if I start a new project, is because I have already a board on my table, I know the board and ensure that ALL the systems in the process are doing the right thing for the right board, is a much more pleasant developer experience IMHO.

**Comment by Vollbrecht** [comment]
yeah but that is not related, to esp-idf-sys itself. We just need to use the MCU env variable inside the templates for the variants, and i think we currently don't even have an option for an esp32c6 since we didn't have support for it so far.

**Pull request closed without merging**
