### PR TITLE
Support remote components and turn component manager on

### LINKED ISSUE #193: using espressif camera,
if i want to use the camear through this crate: https://github.com/espressif/esp32-camera
how should i do, 
```
D:\Development\esp32\esp32cam〉cargo build                                                                                                                           04/13/2023 03:38:38 PM   Compiling esp-idf-sys v0.32.1
error: failed to run custom build command for `esp-idf-sys v0.32.1`

Caused by:
  process didn't exit successfully: `D:\Development\esp32\esp32cam\target\debug\build\esp-idf-sys-90dec810b2d75197\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=ESP_IDF_TOOLS_INSTALL_DIR
  cargo:rerun-if-env-changed=ESP_IDF_SDKCONFIG
  cargo:rerun-if-env-changed=ESP_IDF_SDKCONFIG_DEFAULTS
  cargo:rerun-if-env-changed=MCU
  cargo:rerun-if-env-changed=ESP_IDF_SYS_ROOT_CRATE
  cargo:rerun-if-env-changed=ESP_IDF_VERSION
  cargo:rerun-if-env-changed=ESP_IDF_REPOSITORY
  cargo:rerun-if-env-changed=ESP_IDF_CMAKE_GENERATOR
  cargo:rerun-if-env-changed=IDF_PATH
  cargo:rerun-if-env-changed=EXTRA-COMPONENTS
  cargo:rerun-if-env-changed=ESP_IDF_COMPONENTS
  IDF_PYTHON_ENV_PATH=D:\Development\esp32\esp32cam\.embuild\espressif\python_env\idf5.0_py3.11_env
  ESP_IDF_VERSION=5.0
  PATH=D:\Development\esp32\esp32cam\.embuild\espressif\tools\xtensa-esp32-elf\esp-2022r1-11.2.0\xtensa-esp32-elf\bin;D:\Development\esp32\esp32cam\.embuild\espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin;D:\Development\esp32\esp32cam\.embuild\espressif\tools\ninja\1.10.2\;D:\Development\esp32\esp32cam\.embuild\espressif\python_env\idf5.0_py3.11_env\Scripts;D:\Development\esp32\esp32cam\.embuild\espressif\esp-idf\release-v5.0\tools;%PATH%
  IDF_DEACTIVATE_FILE_PATH=C:\Users\xijhe\AppData\Local\Temp\tmpcb69x_c7idf_3576
  Current system platform: win64
  Skipping cmake@3.20.3 (already installed)
  IDF_PYTHON_ENV_PATH=D:\Development\esp32\esp32cam\.embuild\espressif\python_env\idf5.0_py3.11_env
  ESP_IDF_VERSION=5.0
  PATH=D:\Development\esp32\esp32cam\.embuild\espressif\tools\cmake\3.20.3\bin;D:\Development\esp32\esp32cam\.embuild\espressif\python_env\idf5.0_py3.11_env\Scripts;D:\Development\esp32\esp32cam\.embuild\espressif\esp-idf\release-v5.0\tools;%PATH%
  IDF_DEACTIVATE_FILE_PATH=C:\Users\xijhe\AppData\Local\Temp\tmppx5us2x5idf_19460
  Current system platform: win64
  Skipping xtensa-esp32-elf@esp-2022r1-11.2.0 (already installed)
  Skipping ninja@1.10.2 (already installed)
  Skipping esp32ulp-elf@2.35_20220830 (already installed)
  IDF_PYTHON_ENV_PATH=D:\Development\esp32\esp32cam\.embuild\espressif\python_env\idf5.0_py3.11_env
  ESP_IDF_VERSION=5.0
  PATH=D:\Development\esp32\esp32cam\.embuild\espressif\tools\xtensa-esp32-elf\esp-2022r1-11.2.0\xtensa-esp32-elf\bin;D:\Development\esp32\esp32cam\.embuild\espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin;D:\Development\esp32\esp32cam\.embuild\espressif\tools\ninja\1.10.2\;D:\Development\esp32\esp32cam\.embuild\espressif\python_env\idf5.0_py3.11_env\Scripts;D:\Development\esp32\esp32cam\.embuild\espressif\esp-idf\release-v5.0\tools;%PATH%
  IDF_DEACTIVATE_FILE_PATH=C:\Users\xijhe\AppData\Local\Temp\tmpr8w7q0uyidf_8072
  cargo:rerun-if-changed=D:\Development\esp32\esp32cam\sdkconfig.defaults
  CMAKE_PREFIX_PATH_xtensa-esp32-espidf = None
  CMAKE_PREFIX_PATH_xtensa_esp32_espidf = None
  TARGET_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_xtensa-esp32-espidf = None
  CMAKE_xtensa_esp32_espidf = None
  TARGET_CMAKE = None
  CMAKE = None
  running: "cmake" "D:\\Development\\esp32\\esp32cam\\target\\xtensa-esp32-espidf\\debug\\build\\esp-idf-sys-521a1d1ee1beae17\\out" "-G" "Ninja" "-DCMAKE_TOOLCHAIN_FILE=D:\\Development\\esp32\\esp32cam\\.embuild\\espressif\\esp-idf\\release-v5.0\\tools\\cmake\\toolchain-esp32.cmake" "-DCMAKE_BUILD_TYPE=" "-DPYTHON=D:/Development/esp32/esp32cam/.embuild/espressif/python_env/idf5.0_py3.11_env/Scripts/python.exe" "-DCMAKE_INSTALL_PREFIX=D:\\Development\\esp32\\esp32cam\\target\\xtensa-esp32-espidf\\debug\\build\\esp-idf-sys-521a1d1ee1beae17\\out" "-DCMAKE_C_FLAGS= -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections" "-DCMAKE_CXX_FLAGS= -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections" "-DCMAKE_ASM_FLAGS= -mlongcalls -ffunction-sections -fdata-sections"        
  -- Checking Python dependencies...
  Python requirements are satisfied.
  Constraint file: D:\Development\esp32\esp32cam\.embuild\espressif\espidf.constraints.v5.0.txt
  Requirement files:
   - D:\Development\esp32\esp32cam\.embuild\espressif\esp-idf\release-v5.0\tools\requirements\requirements.core.txt
  Python being checked: D:\Development\esp32\esp32cam\.embuild\espressif\python_env\idf5.0_py3.11_env\Scripts\python.exe
  -- Project sdkconfig file D:/Development/esp32/esp32cam/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-521a1d1ee1beae17/out/sdkconfig
  Loading defaults file D:/Development/esp32/esp32cam/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-521a1d1ee1beae17/out/gen-sdkconfig.defaults...
  Loading defaults file D:/Development/esp32/esp32cam/sdkconfig.defaults...
  D:/Development/esp32/esp32cam/sdkconfig.defaults:12 CONFIG_SPIRAM_SUPPORT was replaced with CONFIG_SPIRAM
  -- App "libespidf" version: 1
  -- Adding linker script D:/Development/esp32/esp32cam/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-521a1d1ee1beae17/out/build/esp-idf/esp_system/ld/memory.ld
  -- Adding linker script D:/Development/esp32/esp32cam/.embuild/espressif/esp-idf/release-v5.0/components/esp_system/ld/esp32/sections.ld.in
  -- Adding linker script D:/Development/esp32/esp32cam/.embuild/espressif/esp-idf/release-v5.0/components/esp_rom/esp32/ld/esp32.rom.ld
  -- Adding linker script D:/Development/esp32/esp32cam/.embuild/espressif/esp-idf/release-v5.0/components/esp_rom/esp32/ld/esp32.rom.api.ld
  -- Adding linker script D:/Development/esp32/esp32cam/.embuild/espressif/esp-idf/release-v5.0/components/esp_rom/esp32/ld/esp32.rom.libgcc.ld
  -- Adding linker script D:/Development/esp32/esp32cam/.embuild/espressif/esp-idf/release-v5.0/components/esp_rom/esp32/ld/esp32.rom.newlib-data.ld
  -- Adding linker script D:/Development/esp32/esp32cam/.embuild/espressif/esp-idf/release-v5.0/components/esp_rom/esp32/ld/esp32.rom.syscalls.ld
  -- Adding linker script D:/Development/esp32/esp32cam/.embuild/espressif/esp-idf/release-v5.0/components/soc/esp32/ld/esp32.peripherals.ld
  -- Configuring done
  -- Generating done
  -- Build files have been written to: D:/Development/esp32/esp32cam/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-521a1d1ee1beae17/out/build
  running: "cmake" "--build" "." "--config" "MinSizeRel" "--parallel" "8"
  [1/804] Performing configure step for 'bootloader'
  FAILED: bootloader-prefix/src/bootloader-stamp/bootloader-configure
  cmd.exe /C "cd /D D:\Development\esp32\esp32cam\target\xtensa-esp32-espidf\debug\build\esp-idf-sys-521a1d1ee1beae17\out\build\bootloader && D:\Development\esp32\esp32cam\.embuild\espressif\tools\cmake\3.20.3\bin\cmake.exe -DSDKCONFIG=D:/Development/esp32/esp32cam/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-521a1d1ee1beae17/out/sdkconfig -DIDF_PATH=D:/Development/esp32/esp32cam/.embuild/espressif/esp-idf/release-v5.0 -DIDF_TARGET=esp32 -DPYTHON_DEPS_CHECKED=1 -DPYTHON=D:/Development/esp32/esp32cam/.embuild/espressif/python_env/idf5.0_py3.11_env/Scripts/python.exe -DEXTRA_COMPONENT_DIRS=D:/Development/esp32/esp32cam/.embuild/espressif/esp-idf/release-v5.0/components/bootloader -DPROJECT_SOURCE_DIR=D:/Development/esp32/esp32cam/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-521a1d1ee1beae17/out -GNinja D:/Development/esp32/esp32cam/.embuild/espressif/esp-idf/release-v5.0/components/bootloader/subproject && D:\Development\esp32\esp32cam\.embuild\espressif\tools\cmake\3.20.3\bin\cmake.exe -E touch D:/Development/esp32/esp32cam/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-521a1d1ee1beae17/out/build/bootloader-prefix/src/bootloader-stamp/bootloader-configure"
  CMake Error: The source "D:/Development/esp32/esp32cam/.embuild/espressif/esp-idf/release-v5.0/components/bootloader/subproject/CMakeLists.txt" does not match the source "D:/Development/esp32/esp32cam/.embuild/espressif/esp-idf/release-v4.4/components/bootloader/subproject/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
  [2/804] Building ASM object esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/port/arch/xtensa/expression_with_stack_asm.S.obj
  [3/804] Building ASM object esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/port/arch/xtensa/panic_handler_asm.S.obj
  [4/804] Building C object esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/port/soc/esp32/cache_err_int.c.obj
  [5/804] Building C object esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/port/arch/xtensa/debug_stubs.c.obj
  [6/804] Building C object esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/port/soc/esp32/reset_reason.c.obj
  [7/804] Building C object esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/port/arch/xtensa/panic_arch.c.obj
  [8/804] Building C object esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/port/soc/esp32/system_internal.c.obj
  ninja: build stopped: subcommand failed.

  --- stderr
  Build configuration: BuildConfig {
      esp_idf_tools_install_dir: None,
      esp_idf_sdkconfig: None,
      esp_idf_sdkconfig_defaults: None,
      mcu: None,
      native: NativeConfig {
          esp_idf_version: Some(
              Branch(
                  "release/v5.0",
              ),
          ),
          esp_idf_repository: None,
          esp_idf_cmake_generator: None,
          idf_path: None,
          extra_components: [
              ExtraComponent {
                  component_dirs: [
                      "vendor",
                  ],
                  bindings_header: Some(
                      "src/bindings.h",
                  ),
                  bindings_module: None,
                  manifest_dir: "D:\\Development\\esp32\\esp32cam",
              },
          ],
          esp_idf_components: None,
      },
      esp_idf_sys_root_crate: None,
  }
  Using managed esp-idf repository: RemoteSdk { repo_url: None, git_ref: Branch("release/v5.0") }
  Using esp-idf v5.0.1 at 'D:\Development\esp32\esp32cam\.embuild\espressif\esp-idf\release-v5.0'
  CMake Warning at D:/Development/esp32/esp32cam/.embuild/espressif/esp-idf/release-v5.0/tools/cmake/build.cmake:544 (message):
    "idf_component.yml" file was found for components:

        D:/Development/esp32/esp32cam/vendor/esp32-camera

    However, the component manager is not enabled.
  Call Stack (most recent call first):
    CMakeLists.txt:16 (idf_build_process)


  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1

  build script failed, must exit now', C:\Users\xijhe\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.50\src\lib.rs:1098:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by N3xed**
This adds the ability to specify remote components in the Cargo.toml and the esp-idf component manager is now turned on by default, and it will manage all such remote components (specified on the Rust side, or in esp-idf components).

I've changed the template cmake project structure to turn the component manager on. It now uses the normal project setup with `project.cmake`. It should, in theory, work the exact same, though I haven't tested all of it.

Remote components make use of the component manager, and its `component_idf.yml` file. All specified `remote_component`s actually map to equivalent entries in that file.

They can be specified with the `remote_component` field in an extra component, e.g.:
```toml
[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/mdns", version = "1.2" }
```
Note though that `remote_component` does not accept a list. If you want to have multiple remote components, use multiple extra component entries.
Other than that, the syntax that @daggerrz suggested in https://github.com/esp-rs/esp-idf-sys/pull/220 and https://github.com/esp-rs/embuild/pull/78 is still supported, though `component_refs` is now `remote_component`.
See the docs for all supported fields (the same as the `dependencies` section in the `idf_component.yml`).

As I said, some more testing is still needed, it would be appreciated.
Feedback is also appreciated.

Fixes #193

### CODE REVIEW

**Comment by daggerrz** [comment]
I finally got back and was able to test this. I see the components are downloaded properly, and are part of the build path, but the `cfg` set is the file system "projection" / direcotry name of the component FQN. E.g for `espressif/mdns`, the `cfg` is `esp_idf_comp_espressif__mdns_enabled`

This does not line up with `bindings.h` in `esp-idf-sys`:
https://github.com/esp-rs/esp-idf-sys/blob/7704c645456662821551a5972ae3d3c64e551216/src/include/esp-idf/bindings.h#L183

and in `lib.rs` in `esp-idf-svc`: 
https://github.com/esp-rs/esp-idf-svc/blob/cf0b85c7d92c7382cd87d5abb6b3a1bede70de6f/src/lib.rs#L59

I'm not sure if it's better to use the "bare" component name in the `cfg` to make it compatible with the current bindings or to update the bindings.

For reference, from the build logs:
```
[esp-idf-sys 0.33.1] cargo:rustc-cfg=esp_idf_comp_espressif__mdns_enabled
```

**Comment by N3xed** [comment]
Thanks for testing it.

Yeah, I noticed this aswell. As far as I see it, we could:

1. If we want to support the existing component names, add an exception to `espressif/*` components, so that we also define the same component without the `espressif__` prefix.

     This would only be worth it if we expect further components to become remote components, and/or there are many `cfg`s for these components already in the code.

2. As you said, change the `#[cfg]`s in the code.

I really don't know how much of an effect these name changes have. And whether there will be more and many. Maybe @ivmarkov knows more?

**Comment by ivmarkov** [comment]
Specifically `ESP_IDF_COMP_MDNS_ENABLED` we can't change as we are supporting ESP IDF V4.4 where this component is built in.

How about just adding `|| esp_idf_comp_espressif__mdns_enabled` (in uppercase of course) and then Instruments g `esp-idf-svc` to check both cfgs? I'm not sure we'll see a flood of components leaving the ESP IDF monorepo, so maybe let's not boil the ocean as of yet, just because of mdns?

**Comment by daggerrz** [comment]
> How about just adding `|| esp_idf_comp_espressif__mdns_enabled` (in uppercase of course) and then Instrumenting `esp-idf-svc` to check both cfgs? I'm not sure we'll see a flood of components leaving the ESP IDF monorepo, so maybe let's not boil the ocean as of yet, just because of mdns?

I think this would be very clear in terms of the `esp-idf-svc` code and the solution that has the least potential to cause future confusion due to component name conflict (although it's probably extremely unlikely in the first case). As more components are moved out of IDF, the `esp_idf_comp_espressif__` prefix in the cfgs will make it easy for maintainers immediately identify that a component has in fact been moved out. 

It would also make it easy spot new components that are only "remote" and exist for 5.x that don't exist / have to be maintained in 4.4 at all, but still are added to `esp-idf-svc` (as opposed to a litany of binding crates).

```C
// IDF Provided component. 
#ifdef ESP_IDF_COMP_{component}_ENABLED
...

// Component migrated from IDF to remote in 5.x+, but IDF provided in 4.4
#if defined(ESP_IDF_COMP_{component}_ENABLED) || defined(ESP_IDF_COMP_espressif_{component}_ENABLED)
...

// Remote-only component, only available in 5.x+
#ifdef ESP_IDF_COMP_{namespace}_{component}_ENABLED
...
```

**Comment by daggerrz** [comment]
Can confirm that the current brand works as expected if the `cfg`s also are updated in `esp-idf-svc`. E.g: https://github.com/esp-rs/esp-idf-svc/commit/c69726e14227fd604e6cbf49a255df6e90f3df0b

**Comment by dacut** [comment]
@N3xed, just wanted to make sure you saw the comment over in https://github.com/esp-rs/esp-idf-sys/issues/231#issuecomment-1676189581. It's possible (perhaps likely) I was doing something wrong, but adding this to `Config.toml`:
```
[[package.metadata.esp-idf-sys.extra_components]]
espressif_tinyusb = { name = "espressif/tinyusb", version = "0.15.0_2" }
espressif_esp_tinyusb = { name = "espressif/esp_tinyusb", version = "1.3.1" }
```

Resulted in invalid cfg keys being set (the `.` in the version number is invalid):
```
[issue231 0.1.0] cargo:rustc-cfg=esp_idf_comp_espressif_tinyusb_0.15.0_2_enabled
[issue231 0.1.0] cargo:rustc-cfg=esp_idf_comp_espressif_esp_tinyusb_1.3.1_enabled
error: invalid `--cfg` argument: `esp_idf_comp_espressif_tinyusb_0.15.0_2_enabled` (expected `key` or `key="value"`)
```

This should be set without the version number, but I suspect that's something happening with ESP-IDF.

**Comment by N3xed** [comment]
> @N3xed, just wanted to make sure you saw the comment over in [#231 (comment)](https://github.com/esp-rs/esp-idf-sys/issues/231#issuecomment-1676189581). It's possible (perhaps likely) I was doing something wrong, but adding this to `Config.toml`:
> 
> ```
> [[package.metadata.esp-idf-sys.extra_components]]
> espressif_tinyusb = { name = "espressif/tinyusb", version = "0.15.0_2" }
> espressif_esp_tinyusb = { name = "espressif/esp_tinyusb", version = "1.3.1" }
> ```
> 
> Resulted in invalid cfg keys being set (the `.` in the version number is invalid):
> 
> ```
> [issue231 0.1.0] cargo:rustc-cfg=esp_idf_comp_espressif_tinyusb_0.15.0_2_enabled
> [issue231 0.1.0] cargo:rustc-cfg=esp_idf_comp_espressif_esp_tinyusb_1.3.1_enabled
> error: invalid `--cfg` argument: `esp_idf_comp_espressif_tinyusb_0.15.0_2_enabled` (expected `key` or `key="value"`)
> ```
> 
> This should be set without the version number, but I suspect that's something happening with ESP-IDF.

Yup, I saw it. Haven't had time to get to it yet, though. I'll investigate this and try to finish the PR next weekend.

**Comment by N3xed** [comment]
@dacut I just commented in #231 and it seems to me this is a unrelated issue.

So, this PR seems ready to be merged. I'll do it in the coming days if there are no further issues.

**Comment by dacut** [comment]
@N3xed Sounds good to me. I was probably "holding it wrong" as you point out. 😄

**Pull request merged**
