### PR TITLE
Add build matrix for all targets

### PR DESCRIPTION
**Pull request by svenstaro**
This is a direct follow-up to #101.

### CODE REVIEW

**Comment by ivmarkov** [comment]
@svenstaro Do we need anything for this PR to graduate from the Draft status?

**Comment by svenstaro** [comment]
Ah crap, I kinda forgot about this. Will take a look soon.

**Comment by ivmarkov** [comment]
@svenstaro  Any progress?

**Comment by ivmarkov** [comment]
We have this in the meantime.

**Pull request closed without merging**
