### PR TITLE
choose pcnt implementation on esp-idf 5

### PR DESCRIPTION
**Pull request by liebman**
add feature to select esp-idf 4 pcnt implementation or
esp-idf5 pulse_cnt (v4 always gets pcnt)
default on esp-idf 5 is pulse_cnt

### CODE REVIEW

**Comment by MabezDev** [comment]
Thanks for the PR!

Instead of a new header file, couldn't this be achieved by just modifying `bindings.h` though `#ifdef` based on the esp-idf major version?

**Comment by liebman** [comment]
> Thanks for the PR!
> 
> Instead of a new header file, couldn't this be achieved by just modifying `bindings.h` though `#ifdef` based on the esp-idf major version?

This would prevent choosing the v4 api on v5 (which is supported).

**Comment by shraiwi** [comment]
As of right now, I am currently waiting for this to be merged so that I can use the latest driver. However, @MabezDev mentioned that there was a way to modify the `bindings.h` file so that the new driver is compiled. I tried to do this, by added a few lines to my `Cargo.toml`:

```toml
[package]
name = "fw-esp32-rs-test"
version = "0.1.0"
authors = ["shranav@shraiwi.com <shranav@shraiwi.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.66"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]

default = ["std", "hal", "esp-idf-sys/native"]

pio = ["esp-idf-sys/pio"]
all = ["std", "nightly", "experimental", "embassy"]
hal = ["esp-idf-hal", "embedded-svc", "esp-idf-svc"]
std = ["alloc", "esp-idf-sys/std", "esp-idf-sys/binstart", "embedded-svc?/std", "esp-idf-hal?/std", "esp-idf-svc?/std"]
alloc = ["embedded-svc?/alloc", "esp-idf-hal?/alloc", "esp-idf-svc?/alloc"]
nightly = ["embedded-svc?/nightly", "esp-idf-svc?/nightly"] # Future: "esp-idf-hal?/nightly"
experimental = ["embedded-svc?/experimental", "esp-idf-svc?/experimental"]
embassy = ["esp-idf-hal?/embassy-sync", "esp-idf-hal?/critical-section", "esp-idf-hal?/edge-executor", "esp-idf-svc?/embassy-time-driver", "esp-idf-svc?/embassy-time-isr-queue"]

[dependencies]

derive_more = "0.99.17"

log = { version = "0.4.17", default-features = false }
esp-idf-sys = { version = "0.33", default-features = false }
esp-idf-hal = { version = "0.41", optional = true, default-features = false }
esp-idf-svc = { version = "0.46", optional = true, default-features = false }
embedded-svc = { version = "0.25", optional = true, default-features = false }

[build-dependencies]
embuild = "0.31.2"

[[package.metadata.esp-idf-sys.extra_components]]
bindings_header = "bindings.h" # <= added this
```

And I added `bindings.h` to my project root:

```h
#include "driver/pulse_cnt.h"
```

But this resulted in a compilation error. How do I correctly mark `driver/pulse_cnt.h` for binding generation?

**Comment by liebman** [comment]
@shraiwi I'm fairly sure that this needs to be done in `esp-idf-sys`.  While can include your own compiled components via bindings_header I don't think you can use this to modify `esp-idf-sys`.

**Comment by shraiwi** [comment]
So would the solution be to fork `esp-idf-sys` and `#include` the new PCNT files in `bindings.h`?

**Comment by liebman** [comment]
yes but the new driver is not implemented in `esp-idf-hal` and that may fail to compile as it will still look for the old one..

**Comment by shraiwi** [comment]
Okay. Thank you for the information! I think for now I'll just use the legacy driver.

**Comment by dacut** [comment]
Equivalent code has been merged via https://github.com/esp-rs/esp-idf-sys/pull/229; this can be closed.

**Comment by ivmarkov** [comment]
Closing in favor of #230

**Pull request closed without merging**
